# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"update_attributes": "00_plotped.ipynb",
         "get_args": "00_plotped.ipynb"}

modules = ["plot.py"]

doc_url = "https://changebio.github.io/graphped/"

git_url = "https://github.com/changebio/graphped/tree/main/"

def custom_doc_links(name): return None
