
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-08-14T16:43:39+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "44f0c7e8cf903208c9df2ce7e9d26800de6d5c86",
 "version": "0.post.dev1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
