
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-08-16T14:33:36+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "d87cb41e20312a967d2e4b86501a373e187c81ba",
 "version": "0.2.24.post0.dev6"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
