
# This file was generated by 'versioneer.py' (0.23) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-08-13T23:57:20+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "5ec4257f01bb3e6cd716b5e52150213e99d82f94",
 "version": "0.3.10"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
