# -*- coding: utf-8 -*-

"""
pqapiv2

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class BankAccountStatusTypesEnum(object):

    """Implementation of the '_bankAccountStatusTypes' enum.

    Current verification status type of the bank account

    Attributes:
        DELETED: TODO: type description here.
        ACTIVE: TODO: type description here.
        PENDING_VERIFICATION: TODO: type description here.

    """

    DELETED = 'DELETED'

    ACTIVE = 'ACTIVE'

    PENDING_VERIFICATION = 'PENDING_VERIFICATION'
