# -*- coding: utf-8 -*-

"""
pqapiv2

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class ClientPaymentId(object):

    """Implementation of the '_clientPaymentId' model.

    Unique value provided by the client for the payment, utilized for
    reference and de-duplication.

    Attributes:
        client_payment_id (string): Unique value provided by the client for
            the payment.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "client_payment_id": 'clientPaymentId'
    }

    def __init__(self,
                 client_payment_id=None):
        """Constructor for the ClientPaymentId class"""

        # Initialize members of the class
        self.client_payment_id = client_payment_id

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary
        client_payment_id = dictionary.get('clientPaymentId')

        # Return an object of this model
        return cls(client_payment_id)
