# -*- coding: utf-8 -*-

"""
pqapiv2

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class ClientTransferId(object):

    """Implementation of the '_clientTransferId' model.

    Unique value provided by the client for the transfer, utilized for
    reference and deduplication.

    Attributes:
        client_transfer_id (string): Unique value provided by the client for
            the transfer.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "client_transfer_id": 'clientTransferId'
    }

    def __init__(self,
                 client_transfer_id=None):
        """Constructor for the ClientTransferId class"""

        # Initialize members of the class
        self.client_transfer_id = client_transfer_id

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary
        client_transfer_id = dictionary.get('clientTransferId')

        # Return an object of this model
        return cls(client_transfer_id)
