# -*- coding: utf-8 -*-

"""
pqapiv2

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class IdentityVerificationProviderReference(object):

    """Implementation of the '_identityVerificationProviderReference' model.

    Provider reference used for performing identity checks for the provider

    Attributes:
        idv_provider_reference (string): IDV provider unique ID for the IDV
            check performed

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "idv_provider_reference": 'idvProviderReference'
    }

    def __init__(self,
                 idv_provider_reference=None):
        """Constructor for the IdentityVerificationProviderReference class"""

        # Initialize members of the class
        self.idv_provider_reference = idv_provider_reference

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary
        idv_provider_reference = dictionary.get('idvProviderReference')

        # Return an object of this model
        return cls(idv_provider_reference)
