# -*- coding: utf-8 -*-

"""
pqapiv2

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class KeyValuePairLanguageTypeString(object):

    """Implementation of the '_keyValuePairLanguageTypeString' model.

    Localized requirement description for display purposes

    Attributes:
        language (LanguageTypesEnum): Language type in IETF's BCP 47 format
        translation (string): Translated string in the specified language

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "language": 'language',
        "translation": 'translation'
    }

    def __init__(self,
                 language=None,
                 translation=None):
        """Constructor for the KeyValuePairLanguageTypeString class"""

        # Initialize members of the class
        self.language = language
        self.translation = translation

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary
        language = dictionary.get('language')
        translation = dictionary.get('translation')

        # Return an object of this model
        return cls(language,
                   translation)
