# -*- coding: utf-8 -*-

"""
pqapiv2

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class SourceToken(object):

    """Implementation of the '_sourceToken' model.

    Unique identifier representing the source of funds.

    Attributes:
        source_token (string): Unique identifier representing the source of
            funds.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "source_token": 'sourceToken'
    }

    def __init__(self,
                 source_token=None):
        """Constructor for the SourceToken class"""

        # Initialize members of the class
        self.source_token = source_token

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary
        source_token = dictionary.get('sourceToken')

        # Return an object of this model
        return cls(source_token)
