# -*- coding: utf-8 -*-

"""
pqapiv2

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class TransferStatusTypesEnum(object):

    """Implementation of the '_transferStatusTypes' enum.

    Current status of a transfer

    Attributes:
        QUOTED: TODO: type description here.
        PENDING: TODO: type description here.
        SCHEDULED: TODO: type description here.
        COMPLETED: TODO: type description here.
        CANCELLED: TODO: type description here.
        RETURNED: TODO: type description here.
        FAILED: TODO: type description here.
        EXPIRED: TODO: type description here.
        VERIFICATION_HOLD: TODO: type description here.

    """

    QUOTED = 'QUOTED'

    PENDING = 'PENDING'

    SCHEDULED = 'SCHEDULED'

    COMPLETED = 'COMPLETED'

    CANCELLED = 'CANCELLED'

    RETURNED = 'RETURNED'

    FAILED = 'FAILED'

    EXPIRED = 'EXPIRED'

    VERIFICATION_HOLD = 'VERIFICATION_HOLD'
