# coding: utf-8

"""
    FABRIC Core API

    FABRIC Core API  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: stealey@unc.edu
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.announcements_api import AnnouncementsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestAnnouncementsApi(unittest.TestCase):
    """AnnouncementsApi unit test stubs"""

    def setUp(self):
        self.api = AnnouncementsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_announcements_get(self):
        """Test case for announcements_get

        Search for FABRIC Announcements  # noqa: E501
        """
        pass

    def test_announcements_post(self):
        """Test case for announcements_post

        Create a new FABRIC Announcement  # noqa: E501
        """
        pass

    def test_announcements_uuid_delete(self):
        """Test case for announcements_uuid_delete

        Delete Announcement as Portal Admin  # noqa: E501
        """
        pass

    def test_announcements_uuid_get(self):
        """Test case for announcements_uuid_get

        Announcement details by UUID  # noqa: E501
        """
        pass

    def test_announcements_uuid_patch(self):
        """Test case for announcements_uuid_patch

        Update Announcement details as Portal Admin  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
