
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-08-16T00:17:33+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "3a6048ef61eb45bda58b92b1ebc565074915bdf2",
 "version": "0.2.24.post0.dev4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
