# Generated by Django 2.2.8 on 2022-08-08 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0013_auto_20220610_1616'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='code',
        ),
    ]
