from .animation import animation
from .button import button
from .callback_query import callback_query
from .command import command
from .contact import contact
from .document import document
from .message import message
from .my_chat_member import my_chat_member
from .photo import photo
from .start import start
from .text import text
