"""__init__.py"""


from mastapy._internal.dummy_base_class_importer import _DummyBaseClassImport


with _DummyBaseClassImport():
    from ._989 import AddendumModificationDistributionRule
    from ._990 import BacklashSpecification
    from ._991 import BasicRackProfiles
    from ._992 import CaseHardeningProperties
    from ._993 import CreateNewSuitableCutterOption
    from ._994 import CrossedAxisCylindricalGearPair
    from ._995 import CrossedAxisCylindricalGearPairLineContact
    from ._996 import CrossedAxisCylindricalGearPairPointContact
    from ._997 import CylindricalGearAbstractRack
    from ._998 import CylindricalGearAbstractRackFlank
    from ._999 import CylindricalGearBasicRack
    from ._1000 import CylindricalGearBasicRackFlank
    from ._1001 import CylindricalGearCuttingOptions
    from ._1002 import CylindricalGearDefaults
    from ._1003 import CylindricalGearDesign
    from ._1004 import CylindricalGearDesignConstraint
    from ._1005 import CylindricalGearDesignConstraints
    from ._1006 import CylindricalGearDesignConstraintsDatabase
    from ._1007 import CylindricalGearDesignConstraintSettings
    from ._1008 import CylindricalGearFlankDesign
    from ._1009 import CylindricalGearMeshDesign
    from ._1010 import CylindricalGearMeshFlankDesign
    from ._1011 import CylindricalGearMicroGeometrySettings
    from ._1012 import CylindricalGearMicroGeometrySettingsDatabase
    from ._1013 import CylindricalGearMicroGeometrySettingsItem
    from ._1014 import CylindricalGearPinionTypeCutter
    from ._1015 import CylindricalGearPinionTypeCutterFlank
    from ._1016 import CylindricalGearProfileMeasurement
    from ._1017 import CylindricalGearProfileMeasurementType
    from ._1018 import CylindricalGearProfileModifications
    from ._1019 import CylindricalGearSetDesign
    from ._1020 import CylindricalGearSetFlankDesign
    from ._1021 import CylindricalGearSetMacroGeometryOptimiser
    from ._1022 import CylindricalGearSetManufacturingConfigurationSelection
    from ._1023 import CylindricalGearSetMicroGeometrySettings
    from ._1024 import CylindricalGearTableMGItemDetail
    from ._1025 import CylindricalGearTableWithMGCharts
    from ._1026 import CylindricalGearToothThicknessSpecification
    from ._1027 import CylindricalMeshAngularBacklash
    from ._1028 import CylindricalMeshedGear
    from ._1029 import CylindricalMeshedGearFlank
    from ._1030 import CylindricalMeshLinearBacklashSpecification
    from ._1031 import CylindricalPlanetaryGearSetDesign
    from ._1032 import CylindricalPlanetGearDesign
    from ._1033 import DIN3967AllowanceSeries
    from ._1034 import DIN3967ToleranceSeries
    from ._1035 import DoubleAxisScaleAndRange
    from ._1036 import FinishToothThicknessDesignSpecification
    from ._1037 import GearFitSystems
    from ._1038 import GearManufacturingConfigSetupViewModel
    from ._1039 import GearSetManufacturingConfigurationSetup
    from ._1040 import GeometrySpecificationType
    from ._1041 import HardenedMaterialProperties
    from ._1042 import HardnessProfileCalculationMethod
    from ._1043 import HeatTreatmentType
    from ._1044 import ISO6336Geometry
    from ._1045 import ISO6336GeometryBase
    from ._1046 import ISO6336GeometryForShapedGears
    from ._1047 import ISO6336GeometryManufactured
    from ._1048 import LinearBacklashSepcification
    from ._1049 import LTCALoadCaseModifiableSettings
    from ._1050 import LtcaSettings
    from ._1051 import MicroGeometryConvention
    from ._1052 import MicroGeometryProfileConvention
    from ._1053 import Micropitting
    from ._1054 import NamedPlanetAssemblyIndex
    from ._1055 import NamedPlanetSideBandAmplitudeFactor
    from ._1056 import ReadonlyToothThicknessSpecification
    from ._1057 import RelativeMeasurementViewModel
    from ._1058 import RelativeValuesSpecification
    from ._1059 import RootStressSurfaceChartOption
    from ._1060 import Scuffing
    from ._1061 import ScuffingCoefficientOfFrictionMethods
    from ._1062 import ScuffingTemperatureMethodsAGMA
    from ._1063 import ScuffingTemperatureMethodsISO
    from ._1064 import ShaperEdgeTypes
    from ._1065 import SpurGearLoadSharingCodes
    from ._1066 import StandardRack
    from ._1067 import StandardRackFlank
    from ._1068 import SurfaceRoughness
    from ._1069 import ThicknessType
    from ._1070 import TiffAnalysisSettings
    from ._1071 import TipAlterationCoefficientMethod
    from ._1072 import TolerancedMetalMeasurements
    from ._1073 import TolerancedValueSpecification
    from ._1074 import ToothFlankFractureAnalysisSettings
    from ._1075 import ToothThicknessSpecification
    from ._1076 import ToothThicknessSpecificationBase
    from ._1077 import TypeOfMechanismHousing
    from ._1078 import Usage
