# coding: utf-8

"""
    FABRIC Core API

    FABRIC Core API  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: stealey@unc.edu
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.whoami_api import WhoamiApi  # noqa: E501
from swagger_client.rest import ApiException


class TestWhoamiApi(unittest.TestCase):
    """WhoamiApi unit test stubs"""

    def setUp(self):
        self.api = WhoamiApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_whoami_get(self):
        """Test case for whoami_get

        Who am I?  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
