
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-08-12T17:00:40+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "17233845c77216128315fbc48e53a5485f4aff01",
 "version": "2.0.19"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
