# coding: utf-8

"""
    FABRIC Core API

    FABRIC Core API  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: stealey@unc.edu
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.status404_not_found_errors import Status404NotFoundErrors  # noqa: E501
from swagger_client.rest import ApiException


class TestStatus404NotFoundErrors(unittest.TestCase):
    """Status404NotFoundErrors unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testStatus404NotFoundErrors(self):
        """Test Status404NotFoundErrors"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.status404_not_found_errors.Status404NotFoundErrors()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
