
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-08-18T17:01:38-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "da3d8f6918db8fa280707865e574b0deaf632873",
 "version": "0.2.25.post0.dev16"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
