
# This file was generated by 'versioneer.py' (0.22) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-08-13T12:07:32+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "69d78ad1871321c0a0507688c8c7a3855aafff3b",
 "version": "1.0.post0.dev14"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
