# coding: utf-8

"""
    ZIOS api

    ZIOS operations  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from zios.configuration import Configuration


class InlineResponse20071ShowVcsresponse(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'status': 'int',
        'vcs_count': 'int',
        'vcs': 'list[InlineResponse20071ShowVcsresponseVcs]'
    }

    attribute_map = {
        'status': 'status',
        'vcs_count': 'vcs-count',
        'vcs': 'vcs'
    }

    def __init__(self, status=None, vcs_count=None, vcs=None, _configuration=None):  # noqa: E501
        """InlineResponse20071ShowVcsresponse - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._status = None
        self._vcs_count = None
        self._vcs = None
        self.discriminator = None

        if status is not None:
            self.status = status
        if vcs_count is not None:
            self.vcs_count = vcs_count
        if vcs is not None:
            self.vcs = vcs

    @property
    def status(self):
        """Gets the status of this InlineResponse20071ShowVcsresponse.  # noqa: E501


        :return: The status of this InlineResponse20071ShowVcsresponse.  # noqa: E501
        :rtype: int
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this InlineResponse20071ShowVcsresponse.


        :param status: The status of this InlineResponse20071ShowVcsresponse.  # noqa: E501
        :type: int
        """

        self._status = status

    @property
    def vcs_count(self):
        """Gets the vcs_count of this InlineResponse20071ShowVcsresponse.  # noqa: E501


        :return: The vcs_count of this InlineResponse20071ShowVcsresponse.  # noqa: E501
        :rtype: int
        """
        return self._vcs_count

    @vcs_count.setter
    def vcs_count(self, vcs_count):
        """Sets the vcs_count of this InlineResponse20071ShowVcsresponse.


        :param vcs_count: The vcs_count of this InlineResponse20071ShowVcsresponse.  # noqa: E501
        :type: int
        """

        self._vcs_count = vcs_count

    @property
    def vcs(self):
        """Gets the vcs of this InlineResponse20071ShowVcsresponse.  # noqa: E501


        :return: The vcs of this InlineResponse20071ShowVcsresponse.  # noqa: E501
        :rtype: list[InlineResponse20071ShowVcsresponseVcs]
        """
        return self._vcs

    @vcs.setter
    def vcs(self, vcs):
        """Sets the vcs of this InlineResponse20071ShowVcsresponse.


        :param vcs: The vcs of this InlineResponse20071ShowVcsresponse.  # noqa: E501
        :type: list[InlineResponse20071ShowVcsresponseVcs]
        """

        self._vcs = vcs

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(InlineResponse20071ShowVcsresponse, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InlineResponse20071ShowVcsresponse):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, InlineResponse20071ShowVcsresponse):
            return True

        return self.to_dict() != other.to_dict()
