
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-08-12T16:52:01+0900",
 "dirty": false,
 "error": null,
 "full-revisionid": "1bbecdb97d0857154490f8a04b2c6e4621671abb",
 "version": "1.95.1.dev0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
