
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-08-12T17:07:23+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "699557ed64cef29a4ad8674d5a59327bf715f3ec",
 "version": "0.2.23.post0.dev4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
