"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.message
import typing
import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor = ...

class CheckBookRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    BOOKNAME_FIELD_NUMBER: builtins.int
    bookName: typing.Text = ...

    def __init__(self,
        *,
        bookName : typing.Text = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"bookName",b"bookName"]) -> None: ...
global___CheckBookRequest = CheckBookRequest

class CheckBookResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    EXISTS_FIELD_NUMBER: builtins.int
    exists: builtins.bool = ...

    def __init__(self,
        *,
        exists : builtins.bool = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"exists",b"exists"]) -> None: ...
global___CheckBookResponse = CheckBookResponse
