
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-08-17T14:49:12-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "11a55694abf844cb7b23b14eb228d5d26628eb99",
 "version": "2022.8.17"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
