
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-08-17T16:23:04-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "749fcfc02e34d0b9674c96841958e467eb846888",
 "version": "0.8.0rc1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
