# Generated by Django 3.2.6 on 2021-12-10 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0005_podcast_about_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcast',
            name='bg_colour',
            field=models.CharField(default='ffffff', max_length=8, verbose_name='background'),
        ),
        migrations.AddField(
            model_name='podcast',
            name='bg_grey',
            field=models.CharField(default='f4f0eb', max_length=8, verbose_name='grey background'),
        ),
        migrations.AddField(
            model_name='podcast',
            name='colour_border',
            field=models.CharField(default='f3ece2', max_length=8, verbose_name='border'),
        ),
        migrations.AddField(
            model_name='podcast',
            name='colour_brand',
            field=models.CharField(default='6219ff', max_length=8, verbose_name='brand'),
        ),
        migrations.AddField(
            model_name='podcast',
            name='colour_dark',
            field=models.CharField(default='1c203c', max_length=8, verbose_name='dark'),
        ),
        migrations.AddField(
            model_name='podcast',
            name='colour_error',
            field=models.CharField(default='d50000', max_length=8, verbose_name='error messages'),
        ),
        migrations.AddField(
            model_name='podcast',
            name='colour_grey',
            field=models.CharField(default='626265', max_length=8, verbose_name='grey'),
        ),
        migrations.AddField(
            model_name='podcast',
            name='colour_success',
            field=models.CharField(default='008040', max_length=8, verbose_name='success messages'),
        ),
        migrations.AddField(
            model_name='podcast',
            name='colour_text',
            field=models.CharField(default='1c203c', max_length=8, verbose_name='text'),
        ),
        migrations.AddField(
            model_name='podcast',
            name='colour_white',
            field=models.CharField(default='ffffff', max_length=8, verbose_name='white'),
        ),
    ]
