# Generated by Django 3.2.6 on 2021-12-10 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0006_auto_20211210_1207'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcast',
            name='ordering',
            field=models.CharField(choices=[('r', 'reverse-chronological'), ('n', 'episode number')], default='r', max_length=1),
        ),
    ]
