# Generated by Django 3.2.6 on 2022-07-02 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0012_rename_ordering_podcast_episode_ordering'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcast',
            name='contact_form',
            field=models.BooleanField(default=True),
        ),
    ]
