# Generated by Django 3.2.6 on 2022-08-03 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0013_podcast_contact_form'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='transcript',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='episode',
            name='transcript_url',
            field=models.URLField(blank=True, editable=False, max_length=255, null=True, verbose_name='transcript URL'),
        ),
    ]
