
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-08-16T19:17:21+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "1282ddb0d6139340c4b7c47058cc6b8d112ffcab",
 "version": "0.2.24.post0.dev18"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
