
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-08-12T19:58:15+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "58d148b79372af051208bfbde226eb17eef432e3",
 "version": "0.2.23.post0.dev10"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
