
# This file was generated by 'versioneer.py' (0.22) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-08-17T05:13:48+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "f699a94c43833995ce56fd9709dda0601c717b92",
 "version": "0.1.38.post0.dev14"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
