
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-08-17T11:49:43+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "88432f5e4c51bd8c6a4bf1520c55f19d708f4c18",
 "version": "2.0.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
