
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-08-14T02:47:21+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "f79c3373717103cc0bf42b7ba9f1c6e686480a52",
 "version": "0.4.dev2233"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
