VERSION_YEAR = 2022
VERSION_MONTH = int('08')
VERSION_DAY = int('16')
VERSION_HOUR = int('15')
VERSION_MINUTE = int('16')
MAJOR_VERSION = 1
MINOR_VERSION = 10
PATCH_VERSION = 202208161516
version_date = '2022/08/16 15:16'
version = '{}.{}.{}'.format(MAJOR_VERSION, MINOR_VERSION, PATCH_VERSION)
__all__  = ['MAJOR_VERSION', 'MINOR_VERSION', 'PATCH_VERSION', 'version_date', 'version']
