# coding: utf-8

"""
    FABRIC Core API

    FABRIC Core API  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: stealey@unc.edu
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ProjectsPersonnelPatch(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'project_members': 'list[str]',
        'project_owners': 'list[str]'
    }

    attribute_map = {
        'project_members': 'project_members',
        'project_owners': 'project_owners'
    }

    def __init__(self, project_members=None, project_owners=None):  # noqa: E501
        """ProjectsPersonnelPatch - a model defined in Swagger"""  # noqa: E501
        self._project_members = None
        self._project_owners = None
        self.discriminator = None
        if project_members is not None:
            self.project_members = project_members
        if project_owners is not None:
            self.project_owners = project_owners

    @property
    def project_members(self):
        """Gets the project_members of this ProjectsPersonnelPatch.  # noqa: E501


        :return: The project_members of this ProjectsPersonnelPatch.  # noqa: E501
        :rtype: list[str]
        """
        return self._project_members

    @project_members.setter
    def project_members(self, project_members):
        """Sets the project_members of this ProjectsPersonnelPatch.


        :param project_members: The project_members of this ProjectsPersonnelPatch.  # noqa: E501
        :type: list[str]
        """

        self._project_members = project_members

    @property
    def project_owners(self):
        """Gets the project_owners of this ProjectsPersonnelPatch.  # noqa: E501


        :return: The project_owners of this ProjectsPersonnelPatch.  # noqa: E501
        :rtype: list[str]
        """
        return self._project_owners

    @project_owners.setter
    def project_owners(self, project_owners):
        """Sets the project_owners of this ProjectsPersonnelPatch.


        :param project_owners: The project_owners of this ProjectsPersonnelPatch.  # noqa: E501
        :type: list[str]
        """

        self._project_owners = project_owners

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ProjectsPersonnelPatch, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ProjectsPersonnelPatch):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
