
# This file was generated by 'versioneer.py' (0.23) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-08-12T12:20:53+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "7a4594a088cf6b43ede9a2f2ffd3bda57847ebcc",
 "version": "1.17.0.post0.dev101"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
