
# This file was generated by 'versioneer.py' (0.23) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-08-19T03:22:24+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "1ed5c38b3f7fb94939f23d4597474d0615faa146",
 "version": "1.17.0.post0.dev150"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
