
# This file was generated by '_versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-08-17T15:05:31-0600",
 "dirty": false,
 "error": null,
 "full-revisionid": "e672fac5332b1668c3d1e36abcae9f55cfed9adf",
 "version": "1.3.12"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
