
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-08-08T18:50:50+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "603db6aafbc997707b51cf19d8eeb450026ec87e",
 "version": "v22.10.00a220815"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
