VERSION_YEAR = 2022
VERSION_MONTH = int('08')
VERSION_DAY = int('12')
VERSION_HOUR = int('05')
VERSION_MINUTE = int('20')
MAJOR_VERSION = 1
MINOR_VERSION = 9
PATCH_VERSION = 202208120520
version_date = '2022/08/12 05:20'
version = '{}.{}.{}'.format(MAJOR_VERSION, MINOR_VERSION, PATCH_VERSION)
__all__  = ['MAJOR_VERSION', 'MINOR_VERSION', 'PATCH_VERSION', 'version_date', 'version']
