# automatically generated by the FlatBuffers compiler, do not modify

# namespace: flat

import flatbuffers

class PlayerInputBatch(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsPlayerInputBatch(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = PlayerInputBatch()
        x.Init(buf, n + offset)
        return x

    # PlayerInputBatch
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # PlayerInputBatch
    def PlayerInputs(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from .PlayerInput import PlayerInput
            obj = PlayerInput()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # PlayerInputBatch
    def PlayerInputsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

def PlayerInputBatchStart(builder): builder.StartObject(1)
def PlayerInputBatchAddPlayerInputs(builder, playerInputs): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(playerInputs), 0)
def PlayerInputBatchStartPlayerInputsVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def PlayerInputBatchEnd(builder): return builder.EndObject()
