# coding: utf-8

"""
    FABRIC Core API

    FABRIC Core API  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: stealey@unc.edu
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ApiOptionsOne(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'api_endpoints': 'list[ApiOptionsOneApiEndpoints]',
        'description': 'str',
        'key_value_pairs': 'dict(str, str)',
        'name': 'str'
    }

    attribute_map = {
        'api_endpoints': 'api_endpoints',
        'description': 'description',
        'key_value_pairs': 'key_value_pairs',
        'name': 'name'
    }

    def __init__(self, api_endpoints=None, description=None, key_value_pairs=None, name=None):  # noqa: E501
        """ApiOptionsOne - a model defined in Swagger"""  # noqa: E501
        self._api_endpoints = None
        self._description = None
        self._key_value_pairs = None
        self._name = None
        self.discriminator = None
        if api_endpoints is not None:
            self.api_endpoints = api_endpoints
        if description is not None:
            self.description = description
        if key_value_pairs is not None:
            self.key_value_pairs = key_value_pairs
        if name is not None:
            self.name = name

    @property
    def api_endpoints(self):
        """Gets the api_endpoints of this ApiOptionsOne.  # noqa: E501


        :return: The api_endpoints of this ApiOptionsOne.  # noqa: E501
        :rtype: list[ApiOptionsOneApiEndpoints]
        """
        return self._api_endpoints

    @api_endpoints.setter
    def api_endpoints(self, api_endpoints):
        """Sets the api_endpoints of this ApiOptionsOne.


        :param api_endpoints: The api_endpoints of this ApiOptionsOne.  # noqa: E501
        :type: list[ApiOptionsOneApiEndpoints]
        """

        self._api_endpoints = api_endpoints

    @property
    def description(self):
        """Gets the description of this ApiOptionsOne.  # noqa: E501


        :return: The description of this ApiOptionsOne.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this ApiOptionsOne.


        :param description: The description of this ApiOptionsOne.  # noqa: E501
        :type: str
        """

        self._description = description

    @property
    def key_value_pairs(self):
        """Gets the key_value_pairs of this ApiOptionsOne.  # noqa: E501


        :return: The key_value_pairs of this ApiOptionsOne.  # noqa: E501
        :rtype: dict(str, str)
        """
        return self._key_value_pairs

    @key_value_pairs.setter
    def key_value_pairs(self, key_value_pairs):
        """Sets the key_value_pairs of this ApiOptionsOne.


        :param key_value_pairs: The key_value_pairs of this ApiOptionsOne.  # noqa: E501
        :type: dict(str, str)
        """

        self._key_value_pairs = key_value_pairs

    @property
    def name(self):
        """Gets the name of this ApiOptionsOne.  # noqa: E501


        :return: The name of this ApiOptionsOne.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this ApiOptionsOne.


        :param name: The name of this ApiOptionsOne.  # noqa: E501
        :type: str
        """

        self._name = name

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ApiOptionsOne, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ApiOptionsOne):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
