
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-08-11T01:11:34+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "aefb23e9598e8f7b5b9fa21431d3c87f5e7a2395",
 "version": "1.5.8.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
