# Generated by Django 3.2.6 on 2021-09-22 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0002_alter_podcast_domain'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcast',
            name='short_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
