# Generated by Django 3.2.6 on 2022-02-13 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('websub', '0001_initial'),
        ('podcasts', '0007_podcast_ordering'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcast',
            name='subscription',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='websub.subscription'),
        ),
    ]
