# Generated by Django 3.2.6 on 2022-02-13 14:07

from django.db import migrations, models
import pico.podcasts.models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0008_podcast_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcast',
            name='banner',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=pico.podcasts.models.Podcast.upload_banner),
        ),
        migrations.AddField(
            model_name='season',
            name='banner',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=pico.podcasts.models.Season.upload_artwork),
        ),
    ]
