# Generated by Django 3.2.6 on 2022-02-20 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0010_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcast',
            name='head_html',
            field=models.TextField(blank=True, null=True, verbose_name='head HTML'),
        ),
    ]
