
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-08-08T11:27:31-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "8c17a2b1a7c85b24511ec8040e83947f997a7e16",
 "version": "v0.1.8"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
