
# This file was generated by 'versioneer.py' (0.22) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-08-18T08:28:49+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "6b768acf3a5e273ea2b81d30cc4d5cbd16f999d6",
 "version": "4.2rc2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
