
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-08-15T16:44:13-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "ddaa9ddc2eea755cdaf8060269e48d5fa736eaf8",
 "version": "1.6.3rc5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
