
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-08-15T21:50:58+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "a0058634959cd6ed387703759c36107eee7c8140",
 "version": "0.2.24.post0.dev2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
