# Generated by Django 3.2.6 on 2022-02-24 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0011_podcast_head_html'),
    ]

    operations = [
        migrations.RenameField(
            model_name='podcast',
            old_name='ordering',
            new_name='episode_ordering',
        ),
        migrations.AddField(
            model_name='podcast',
            name='ordering',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterModelOptions(
            name='podcast',
            options={'ordering': ('ordering', 'name')},
        ),
    ]
