# Generated by Django 4.0.5 on 2022-06-15 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chatbot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('created_by', models.IntegerField(default=0)),
                ('is_published', models.SmallIntegerField(blank=True, null=True)),
                ('bot_questions_json', models.JSONField(blank=True, null=True)),
                ('brand_name', models.CharField(blank=True, max_length=200, null=True)),
                ('brand_sub_title', models.CharField(blank=True, max_length=200, null=True)),
                ('chatbot_position', models.CharField(default='right', max_length=200)),
                ('chatbot_primary_color', models.CharField(default='#34436A', max_length=200)),
                ('button_background_color', models.CharField(default='#34436A', max_length=200)),
                ('button_text_color', models.CharField(default='#ffffff', max_length=200)),
                ('auto_show', models.CharField(default='true', max_length=200)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.SmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ChatbotDataCollectionDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_token', models.CharField(max_length=150)),
                ('question_code', models.CharField(max_length=255)),
                ('question', models.CharField(max_length=5000)),
                ('answer', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='ChatbotDataCollectionMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=100)),
                ('user_token', models.CharField(max_length=150)),
                ('chatbot_id', models.IntegerField(default=0)),
                ('is_finished', models.IntegerField(default=0)),
                ('submited_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ChatbotJsplumbConnections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chatbot_id', models.IntegerField()),
                ('source', models.CharField(blank=True, max_length=100, null=True)),
                ('target', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChatbotJsplumbFlowchartPositions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chatbot_id', models.IntegerField()),
                ('question_box_id', models.CharField(blank=True, max_length=100, null=True)),
                ('position', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='ChatbotNextQuestionOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chatbot_id', models.IntegerField()),
                ('question_id', models.IntegerField()),
                ('option_key', models.CharField(max_length=100)),
                ('next_question', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ChatbotQuestionOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id', models.IntegerField()),
                ('label', models.CharField(blank=True, max_length=500, null=True)),
                ('value', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChatbotQuestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_code', models.CharField(max_length=100, unique=True)),
                ('chatbot_id', models.IntegerField()),
                ('question', models.CharField(max_length=500)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('field_type', models.IntegerField()),
                ('expected_answer', models.CharField(blank=True, max_length=1000, null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.SmallIntegerField(default=0)),
            ],
        ),
    ]
