
# This file was generated by 'versioneer.py' (0.22) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-08-18T09:01:17+0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "65f23eb29071280a7b46709e4dcc4945d854b83c",
 "version": "1.5.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
