# -*- coding: utf-8 -*-

"""
pqapiv2

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class BankAccountOwnershipTypesEnum(object):

    """Implementation of the '_bankAccountOwnershipTypes' enum.

    Account ownership types

    Attributes:
        PERSONAL: TODO: type description here.
        BUSINESS: TODO: type description here.

    """

    PERSONAL = 'PERSONAL'

    BUSINESS = 'BUSINESS'
