# -*- coding: utf-8 -*-

"""
pqapiv2

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class CardNetworkTypesEnum(object):

    """Implementation of the '_cardNetworkTypes' enum.

    Major credit card network types

    Attributes:
        VISA: TODO: type description here.
        MASTER_CARD: TODO: type description here.

    """

    VISA = 'VISA'

    MASTER_CARD = 'MASTER_CARD'
