# -*- coding: utf-8 -*-

"""
pqapiv2

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class Cvv(object):

    """Implementation of the '_cvv' model.

    Three- or four-digit Card Verification Value (CVV) number displayed on the
    back of a credit or debit card

    Attributes:
        cvv (string): Card Verification Value (CVV) on the credit card or
            debit card. (3-digit number on VISA®, MasterCard® branded credit
            and debit cards)

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "cvv": 'cvv'
    }

    def __init__(self,
                 cvv=None):
        """Constructor for the Cvv class"""

        # Initialize members of the class
        self.cvv = cvv

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary
        cvv = dictionary.get('cvv')

        # Return an object of this model
        return cls(cvv)
