# -*- coding: utf-8 -*-

"""
pqapiv2

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""
from pqapiv2.models.fx_object import FxObject


class Fx(object):

    """Implementation of the '_fx' model.

    The details of the country's foreign exchange currency.

    Attributes:
        fx (FxObject): Currency conversion object details

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "fx": 'fx'
    }

    def __init__(self,
                 fx=None):
        """Constructor for the Fx class"""

        # Initialize members of the class
        self.fx = fx

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary
        fx = FxObject.from_dictionary(dictionary.get('fx')) if dictionary.get('fx') else None

        # Return an object of this model
        return cls(fx)
