# -*- coding: utf-8 -*-

"""
pqapiv2

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class GenderTypesEnum(object):

    """Implementation of the '_genderTypes' enum.

    Gender as a user identifies

    Attributes:
        MALE: TODO: type description here.
        FEMALE: TODO: type description here.
        NOT_SPECIFIED: TODO: type description here.

    """

    MALE = 'MALE'

    FEMALE = 'FEMALE'

    NOT_SPECIFIED = 'NOT_SPECIFIED'
