# -*- coding: utf-8 -*-

"""
pqapiv2

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class KeyValueBankCountryCountryTypes(object):

    """Implementation of the '_keyValueBankCountryCountryTypes' model.

    TODO: type model description here.

    Attributes:
        key (string): TODO: type description here.
        value (CountryTypesEnum): Two-digit country code types

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "key": 'key',
        "value": 'value'
    }

    def __init__(self,
                 key='BANK_COUNTRY',
                 value=None):
        """Constructor for the KeyValueBankCountryCountryTypes class"""

        # Initialize members of the class
        self.key = key
        self.value = value

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary
        key = dictionary.get("key") if dictionary.get("key") else 'BANK_COUNTRY'
        value = dictionary.get('value')

        # Return an object of this model
        return cls(key,
                   value)
