# -*- coding: utf-8 -*-

"""
pqapiv2

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class PrepaidCardReplacementReasonTypesEnum(object):

    """Implementation of the '_prepaidCardReplacementReasonTypes' enum.

    Reason for card replacement. In certain programs, the replacement reason
    code impacts replacement cost and responsibility.

    Attributes:
        LOST: TODO: type description here.
        STOLEN: TODO: type description here.
        DAMAGED: TODO: type description here.
        COMPROMISED: TODO: type description here.
        EXPIRED: TODO: type description here.

    """

    LOST = 'LOST'

    STOLEN = 'STOLEN'

    DAMAGED = 'DAMAGED'

    COMPROMISED = 'COMPROMISED'

    EXPIRED = 'EXPIRED'
