# -*- coding: utf-8 -*-

"""
pqapiv2

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class TaxResidentStatus(object):

    """Implementation of the '_taxResidentStatus' model.

    TODO: type model description here.

    Attributes:
        tax_resident_status (TaxResidentStatusTypesEnum): Tax resident status
            type of a country

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "tax_resident_status": 'taxResidentStatus'
    }

    def __init__(self,
                 tax_resident_status=None):
        """Constructor for the TaxResidentStatus class"""

        # Initialize members of the class
        self.tax_resident_status = tax_resident_status

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary
        tax_resident_status = dictionary.get('taxResidentStatus')

        # Return an object of this model
        return cls(tax_resident_status)
