
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-08-12T13:55:37+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "756893a9f8fa36b4cd1e751e61b8b3a824d6a849",
 "version": "2733"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
