
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-08-17T16:48:24+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "06331dd14cbc285e2ece45531f15c1fe003b46f0",
 "version": "0.2.25.post0.dev4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
