
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-08-18T23:00:58+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "e7daa8a0c3e88510a5e8981a71a2aeaffa707856",
 "version": "0.2.25.post0.dev14"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
