# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: graphscope/proto/coordinator_service.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from graphscope.proto import message_pb2 as graphscope_dot_proto_dot_message__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n*graphscope/proto/coordinator_service.proto\x12\x06gs.rpc\x1a\x1egraphscope/proto/message.proto2\xaf\x03\n\x12\x43oordinatorService\x12O\n\x0e\x43onnectSession\x12\x1d.gs.rpc.ConnectSessionRequest\x1a\x1e.gs.rpc.ConnectSessionResponse\x12@\n\tHeartBeat\x12\x18.gs.rpc.HeartBeatRequest\x1a\x19.gs.rpc.HeartBeatResponse\x12>\n\x07RunStep\x12\x16.gs.rpc.RunStepRequest\x1a\x17.gs.rpc.RunStepResponse(\x01\x30\x01\x12\x42\n\tFetchLogs\x12\x18.gs.rpc.FetchLogsRequest\x1a\x19.gs.rpc.FetchLogsResponse0\x01\x12I\n\x0c\x43loseSession\x12\x1b.gs.rpc.CloseSessionRequest\x1a\x1c.gs.rpc.CloseSessionResponse\x12\x37\n\x06\x41\x64\x64Lib\x12\x15.gs.rpc.AddLibRequest\x1a\x16.gs.rpc.AddLibResponseb\x06proto3')



_COORDINATORSERVICE = DESCRIPTOR.services_by_name['CoordinatorService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _COORDINATORSERVICE._serialized_start=87
  _COORDINATORSERVICE._serialized_end=518
# @@protoc_insertion_point(module_scope)
