from enum import Enum


class Category(Enum):
    pass


class Attck(Category):
    InitialAccess = 'TA0001'
    Execution = 'TA0002'
    Persistence = 'TA0003'
    PrivilegeEscalation = 'TA0004'
    DefenseEvasion = 'TA0005'
    CredentialAccess = 'TA0006'
    Discovery = 'TA0007'
    LateralMovement = 'TA0008'
    Collection = 'TA0009'
    Exfiltration = 'TA0010'
    CommandandControl = 'TA0011'
    NetworkEffects = 'TA0038'
    RemoteServiceEffects = 'TA0039'
    Impact = 'TA0040'
    ResourceDevelopment = 'TA0042'
    Reconnaissance = 'TA0043'


class BlackArch(Category):
    AntiForensic = 'anti-forensic'
    Automation = 'automation'
    Automobile = 'automobile'
    Backdoor = 'backdoor'
    Binary = 'binary'
    Bluetooth = 'bluetooth'
    CodeAudit = 'code-audit'
    Config = 'config'
    Cracker = 'cracker'
    Crypto = 'crypto'
    Database = 'database'
    Debugger = 'debugger'
    Decompiler = 'decompiler'
    Defensive = 'defensive'
    Disassembler = 'disassembler'
    Dos = 'dos'
    Drone = 'drone'
    Exploitation = 'exploitation'
    Fingerprint = 'fingerprint'
    Firmware = 'firmware'
    Forensic = 'forensic'
    Fuzzer = 'fuzzer'
    Gpu = 'gpu'
    Hardware = 'hardware'
    Honeypot = 'honeypot'
    Ids = 'ids'
    Keylogger = 'keylogger'
    Malware = 'malware'
    Misc = 'misc'
    Mobile = 'mobile'
    Networking = 'networking'
    Nfc = 'nfc'
    Packer = 'packer'
    Proxy = 'proxy'
    Radio = 'radio'
    Recon = 'recon'
    Reversing = 'reversing'
    Scanner = 'scanner'
    Sniffer = 'sniffer'
    Social = 'social'
    Spoof = 'spoof'
    Stego = 'stego'
    Tunnel = 'tunnel'
    Unpacker = 'unpacker'
    Voip = 'voip'
    Webapp = 'webapp'
    Windows = 'windows'
    Wireless = 'wireless'
