# Generated by Django 3.2.7 on 2022-07-28 06:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.USER_MODEL),
        ('purchase', '0006_alter_subscription__is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.USER_MODEL),
        ),
    ]
