
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-08-18T18:43:11-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "60ed6d377b729462b3d24d31271ee38dee88bb56",
 "version": "0.2.25.post0.dev18"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
