"""
This type stub file was generated by pyright.
"""

from .std import tqdm as std_tqdm

"""
Asynchronous progressbar decorator for iterators.
Includes a default `range` iterator printing to `stderr`.

Usage:
>>> from tqdm.asyncio import trange, tqdm
>>> async for i in trange(10):
...     ...
"""
__author__ = ...
__all__ = ['tqdm_asyncio', 'tarange', 'tqdm', 'trange']
class tqdm_asyncio(std_tqdm):
    """
    Asynchronous-friendly version of tqdm (Python 3.6+).
    """
    def __init__(self, iterable=..., *args, **kwargs) -> None:
        ...
    
    def __aiter__(self): # -> Self@tqdm_asyncio:
        ...
    
    async def __anext__(self):
        ...
    
    def send(self, *args, **kwargs):
        ...
    
    @classmethod
    def as_completed(cls, fs, *, loop=..., timeout=..., total=..., **tqdm_kwargs): # -> Generator[Unknown, None, None]:
        """
        Wrapper for `asyncio.as_completed`.
        """
        ...
    
    @classmethod
    async def gather(cls, *fs, loop=..., timeout=..., total=..., **tqdm_kwargs): # -> list[Unknown]:
        """
        Wrapper for `asyncio.gather`.
        """
        ...
    


def tarange(*args, **kwargs): # -> tqdm_asyncio:
    """
    A shortcut for `tqdm.asyncio.tqdm(range(*args), **kwargs)`.
    """
    ...

tqdm = tqdm_asyncio
trange = ...
